name: Deploy
run-name: Deploy to ${{inputs.env}}
on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: What environment to depoly?
        required: true
        options:
          - jr-dev

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  VITE_APP_GMAP_API_KEY: ${{ secrets.VITE_APP_GMAP_API_KEY }}
  AWS_DEFAULT_REGION: ap-southeast-2
  CRM_ENV: ${{ inputs.env }}

jobs:
  deploy_backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build ${{inputs.env}}
        run: make build_backend

      - name: Install
        run: npm install -g aws-cdk

      - name: Deploy ${{inputs.env}}
        run: make deploy_backend
